name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *"   # updates every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Generate Stats Card
        uses: anuraghazra/github-readme-stats@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: AbhayKTS
          show_icons: true
          bg_color: 000000
          theme: dark
          border_color: ff2e2e
          text_color: c7c7c7
          title_color: ff2e2e
          icon_color: ff2e2e
          border_radius: 10
          include_all_commits: true
          repo: AbhayKTS/AbhayKTS
          output_dir: ./stats

      - name: Commit Stats Image
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add stats/*
          git commit -m "Update stats" || echo "No changes"
          git push
